name: Building apps
on: [push, workflow_dispatch]
jobs: 
  building_front:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - run: |
          cd client
          npm ci
          npm run lintstyles
          npm run lint
          npm run typecheck
          npm run test
          npm run build
          ls -la
  building_backend:
    runs-on: self-hosted
    # services:
    #   postgres:
    #     image: postgres
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: postgres
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    #     ports:
    #       - 5432:5432
    #   nginx:
    #     image: nginx
    #     ports:
    #       - 80:80
    # env:
    #   DATABASE_URL: postgresql://postgres:postgres@localhost:5432/loft_furniture?schema=public
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - run: |
          cd server
          npm ci
          cd src
          npx prisma db push
          cd ..
          npm run lint
          npm run build
          npm run start

