name: Building apps
on: [push, workflow_dispatch]
jobs:
  building_front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - run: |
          cd client
          npm ci
          npm run lintstyles
          npm run lint
          npm run typecheck
          npm run test
          npm run build
  # building_backend:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: 🚀 Deploy to Render.com
  #       uses: bankfliptech/deploy-to-render@v1
  #       with:
  #         serviceId: ${{ secrets.RENDER_SERVICE_ID }}
  #         apiKey: ${{ secrets.RENDER_API_KEY }}
  #         deployHookURL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
